### ISSUE TITLE
Implement automated functional testing framework to ease the PR process

### ISSUE THREAD

**Issue by saralab** [blockstack/stacks-blockchain-api#1002]

**Comment by zone117x** [comment]
We've had a few syncs with QA team and others to break this task down. So far we've come up with two approaches. h/t to @timstackblock and @Eshwari007 for research, documentation, and suggestions 🙏 

### 1) Implement a new kind of test suite within the API repo using a BDD oriented framework
One suggestion is to use [postman's bdd testing framework](https://ganeshsirsi.medium.com/getting-started-with-postman-bdd-api-testing-41013788c31e). 

I've looked into how this development flow works, and AFAIK tests have to be written using postman's web UI, then, manually exported into a postman collection file, committed to the repo, then can be ran in github CI with some tools. So the result is postman collection.json file(s) with embedded js test code snippets, e.g.:
https://github.com/gururajhm/postmancontracttest/blob/da48a3a6434ed6d01c81e1e6fc984cead8fa6dbd/APIContractTest.postman_collection.json#L66-L79

This workflow seems strange to me, but curious to hear other thoughts /cc @rafaelcr @timstackblock @Eshwari007.

Cucumber.js was another mentioned BDD testing framework, see example usage [here](https://github.com/cucumber-examples/cucumber-js-examples/tree/main/examples/typescript-node), and example of REST API testing [here](https://github.com/ynmanware/nodejs-bdd/tree/master/src). It seems like this would fit our development workflow better than the postman approach. However, I'm not 100% sold on the value added by implementing e2e tests with this new framework and syntax. Their [docs](https://cucumber.io/docs/guides/api-automation/ ) state that cucumber is designed for testing web UIs rather than APIs, and points to [pactumjs](https://github.com/pactumjs/pactum) as an API testing framework, which is essentially jest/mocha/supertest (what we're already using in the repo) that can optionally integrate with cucumber.js. Looking at the two pactumjs examples, one using mocha and the other using cucumber, it's still not clear to me how cucumber is beneficial. 

Additionally, any in-repo test suites need to be provided with useful, real-world looking data. @rafaelcr had the suggestion of using event-replay tsv files, where we could "slice" event logs from real world time ranges containing useful/interesting chain behavior. We have precedent for this, where a few types of re-org behavior is isolated in [different tsv files](https://github.com/hirosystems/stacks-blockchain-api/tree/master/src/tests/event-replay-logs) and [tested](https://github.com/hirosystems/stacks-blockchain-api/blob/master/src/tests/microblocks-tests.ts).

### 2) Implement CI/CD flows so that a PR in the API repo automatically triggers tests in Explorer, web wallet, and desktop wallet repos

@timstackblock put together a chart of how this would look:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/1447546/155135202-640d4acf-a508-4136-a456-d739820cb3b7.png">


This seems like an easy win where we can leverage a lot of existing tests, however, we don't currently have a way to automatically spin up new mainnet or testnet API instances to use for this purpose. @CharlieC3 has made a lot of progress in the ability to spin up new instances relatively quickly, but will not work for major-version bumps where event-replay is required. We'll need to discuss this further in upcoming sync.

**Comment by timstackblock** [comment]
I have pushed the following PR https://github.com/hirosystems/stacks-wallet-web/pull/2389 

This PR creates a separate test build path and test directories to run browser automated test against the API network URL https://stacks-node-api-inactive.stacks.co/extended/v1/tx

To run the test do the following:
yarn install
yarn build:test-api
yarn test:integration-api

Next steps will be to put the URL https://stacks-node-api-inactive.stacks.co/extended/v1/tx into an environment variable and have the scripts read the environment variable. This will clear the path for when the API URL is created by Vercel and passed into an environment variable. Our goal is to build a script that can pick that variable up and use it for the test.

**Comment by timstackblock** [comment]
Api Automation test are running in CI please see the 2 links below for an update

https://github.com/hirosystems/stacks-blockchain-api/issues/1493

https://github.com/hirosystems/apiTest
