### ISSUE TITLE
Review error handling

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#173]
We should ensure that all errors returned by the API follow the same structure and have an appropriate error response code. For the base structure, I'd propose RFC 7807:

```json
{
  "type": "https://example.com/probs/out-of-credit", 
  "title": "You do not have enough credit.", 
  "detail": "Your current balance is 30, but that costs 50.",
}
```

We'd need docs URLs for these to work. This will require us to document errors in our docs, which is a great thing I'd argue.

**Comment by zone117x** [comment]
I think we can possibly close this issue. 
All sidecar endpoints that result in a non-2xx status code return a json object with an `error` property. This is already being used by some consumer projects which do something like:
```js
const result = await fetch(...)
if (!result.ok) {
  const error = await result.json();
  throw new Error(error);
}
```

Additionally, I _think_ the core-node proxied endpoints are returning a similar error structure (going off memory since I can't seem to get core-node to error atm). And if we did something like standardize on RFC 7807, we'd wouldn't want to be doing transforms on the proxied endpoints, so we'd probably need to make those changes to the rust codebase as well.


Thoughts?

**Comment by agraebe** [comment]
Agreed
