### ISSUE TITLE
Contract call error responses

### ISSUE THREAD

**Issue by agraebe** [blockstack/stacks-blockchain-api#304]
The explorer could show contract call error responses so that evelopers can troubleshoot issues with their contracts

**Comment by zone117x** [comment]
Need more context here. What kind of error response is expected but not currently available?

**Comment by agraebe** [comment]
@aulneau please add your context. this ticket is from the comment on the explorer release planning

**Comment by aulneau** [comment]
@zone117x : currently there are only two error statuses available: `"abort_by_response" | "abort_by_post_condition";`

which results in these error messages:

```tsx
  const failedMessage =
    status === 'abort_by_response'
      ? 'This transaction did not succeed because the transaction was aborted during its execution.'
      : 'This transaction would have succeeded, but was rolled back by a supplied post-condition.';
```

If a contract fails due to a clarity syntax error, it would be good to expose that data to the end user. Basically we'd love to have more verbose error messaging for people to use to debug why a transaction failed.

**Comment by zone117x** [comment]
I believe a syntax error would be shown when the transaction is submitted. Those aborted error statuses are known after a transaction is mined. There's no consistent way to merge these different failures modes. Once is immediate, the other can be minutes later.

**Comment by zone117x** [comment]
Nothing here has changed since my last response. I don't think there is anything the API can do here. Please comment if anyone has any additional questions or concerns.
