### ISSUE TITLE
Detect mainnet/testnet addresses and perform a 302 redirect 

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain-api#362]
When the node is running in a different network mode than that of a given address, for example, running in testnet but passed a mainnet STX address, it should detect, convert, and return a 302 redirect to the expected address. 

Should be done on at least the `/address/*` and `/search` endpoints. 

This will help users experimenting with Stacks 1.0 data in testnet using their known mainnet address.

**Comment by zone117x** [comment]
@diwakergupta @aulneau what are your thoughts on making it easy for users test with their Stacks 1.0 data? The above API feature is one option. @diwakergupta suggested having a form (I'm guessing on the explorer)?

Thoughts?

**Comment by aulneau** [comment]
I personally think the best UX would be where we do this on the API side of things, and provide a small but clear message, something like:

> You searched for a mainnet address, here is the testnet equivalent.

We could do much of this on the client by validating the string as a stx address, and then checking to see if it's mainnnet/testnet -- however because of how things are set up, the explorer is doing no validation currently because the API handles all of that via the search end point. 

We could also do the inverse for testnet -> mainnet addresses.

@diwakergupta you had mentioned concerns around confusion, or it not being clear. Could you speak more to your concerns?

**Comment by diwakergupta** [comment]
> @diwakergupta @aulneau what are your thoughts on making it easy for users test with their Stacks 1.0 data? The above API feature is one option. @diwakergupta suggested having a form (I'm guessing on the explorer)?
> 
> Thoughts?

Sure. Just so I understand the intended behavior:
* testnet API: if given a mainnet address, turn it to testnet address; otherwise no change
* mainnet API: if given a testnet address, turn it into a mainnet address; otherwise no change

Assuming this is the case, no blockers from me. 

> provide a small but clear message, something like:

+1 -- anything we can do to avoid people getting surprised we should. For instance, if I'm looking for my balance on mainnet, but I accidentally end up querying the testnet explorer (or the testnet API) and see a different balance but don't notice that it's actually for the testnet equivalent.

Also @yknl you'd mentioned there's a way to do this in the CLI as well?

**Comment by yknl** [comment]
The CLI can convert between mainnet and testnet addreses with the `convert_address` command. But I don't think it will help with confusion or improve UX in the explorer in this case.

**Comment by agraebe** [comment]
looks like we solved this for the user in the Explorer. The CLI could convert the address, but it seems unclear if that should be done.

**Comment by zone117x** [comment]
Sounds like we can close this? The explorer was the main reason we initially wanted this.
