### ISSUE TITLE
Include STX spend from all transaction types

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/stacks-blockchain-api#369]
Related https://github.com/blockstack/stacks-blockchain-api/pull/367

In the wallet a list of transactions for a given address is displayed. The UI annotates the amount of STX inbound, or outbound, for each transaction.

In the case of a `contract_call` transactions, the list of events must be iterated in order to sum the total (of `stx_asset` `transfer` types).

Ideally, it'd be great if the `ContractCallTransaction` could include an additional property that calculates this, so the client doesn't have to make many additional requests.

**Comment by zone117x** [comment]
Think this is something we must implement. Otherwise, it sounds like any address included in the genesis block allocations would run into problems as the client attempts to paginate through ~330k events to obtain this "STX inbound" value.

**Comment by zone117x** [comment]
This issue has resurfaced with higher priority now that `send-many` contract-call txs are resulting in the same issue.

As in, when an address page wants to show details for a contract-call tx, it only cares about asset transfer events associated with the address (and not the potentially hundreds or thousands of other asset transfer events).

We never really came to solution on what a good API would look like for this. It doesn't really make sense to stuff into the `transaction` object returned by many of the existing APIs, since that would make the returned tx data all of the sudden different depending on which address was being queried. 


The alternative is to either modify the transaction response so that the regular tx data is a child, and extra data (like aggregated address transfers) can be specified as a sibling. So instead of a transaction response directly containing:
```js
{
   // all the typical transaction properties
  ...transcationData
}
```
It could be modified to return something like:
```js
{
  tx: transactionData, // child with all the typical transaction properties
  aggregateAddressTransfers: something[], // new object with the asset transfer info related to the given address
}
```


Modifying the existing endpoint(s) would be a significant breaking change, so I'd propose implementing these in new endpoints. 


Thoughts? @kyranjamie @aulneau

**Comment by agraebe** [comment]
bumping this up again to continue the conversation :)

**Comment by kyranjamie** [comment]
Sorry @zone117x, missed this. 

I'm not a fan of this breaking change idea. It wouldn't expect tx data to be nested like this. Personally, I'd rather have a separate endpoint to query. It would get hammered, and complicate client code, but better this than than messying the tx schema IMO. Which is pretty solid rn, generated types included.

**Preferred option — summarise in tx**
Agree that a tx schema shouldn't changed based on the context of who's receiving. 
But what is the concern in summarising all token transfers in the tx? In some cases it _may_ be thousands but 🤷🏼  What's the issue: Too many kbs of data in the payload, too expensive to query it?

However large, it's relevant information coupled to the tx, so it belongs here, no? 

```js
{
  ...contractCallTx,
  "contact_call_stx_spend": "300 STX", // implicit from sender's address
  "contact_call_stx_transfers": {
    "ST...": "100 STX"
    "ST...": "100 STX"
    "ST...": "100 STX"
  }
}
```

**Secondary option — separate endpoint**
If it really isn't feasible to add to the tx itself. An endpoint with a schema like this is second best:

```yaml
  /extended/v1/tx/{tx_id}/transfers:
    parameters:
      - name: address
        in: query
        description: Filter by receiving/sending stx address transfers
        required: false
        schema:
          type: string
```

**Comment by zone117x** [comment]
> But what is the concern in summarising all token transfers in the tx? In some cases it may be thousands but 🤷🏼 What's the issue: Too many kbs of data in the payload, too expensive to query it?

Yeah, both. Primarily because of the genesis block, which contains ~330,000 transfer events with unique addresses. Depending on the json schema, I think that would be at least 20MB in data (in a compressed txt format it's already ~10MB).

And for blocks where token unlocks occur, I think there's around ~5000 token mint events. 

While these aren't contract-call type txs, we are still solving the same problem. 

The `/extended/v1/tx/{tx_id}/transfers` endpoint seems like it would work. It could also accept an array of txids (as a POST probably), so that clients would only need 1 additional network request to get transfer info for all the non-stx-transfer tx types?

**Comment by kyranjamie** [comment]
If you'll allow me to explore further: Is there's no way we can work around this issue?

20MB is a lot. But when would we request this? Only when viewing the early transactions of an address that has Stacks 1.0 funds? With time, this be a less and less frequent thing to happen? Same for unlock minting events. But we'll be stuck with this API for ever and ever lol.

It doesn't seem like it would be a _crazy_ idea to add special handling only for the genesis block. If this would prevent us having to make an unfortunate API design trade-off. A `?show_genesis=true`, that's off by default. Where we'd skip the stx transfer events for that block only?

**Comment by zone117x** [comment]
> Only when viewing the early transactions of an address that has Stacks 1.0 funds? With time, this be a less and less frequent thing to happen? Same for unlock minting events.

I think you're generally right, except my assumption is that quite a few, if not the majority of the Stacks 1.0 addresses won't end up being very active, and loading the address page for them might be pretty expensive, since most if not all transactions associated will be the unlocking ones (plus genesis). Eventually, loading one of these would involve like 8 of the unlocking/minting transactions, each with ~5000 entries. So depending on schema, could be close to like 2MB?

To your point, those hodler addresses probably won't be accessed often, but would still be a ddos vulnerability. Same with the `?show_genesis=true` option, I don't think we'd be able to enable it at all.

**Comment by zone117x** [comment]
Chatted more about this with @kyranjamie and sounds like we should move ahead with a new endpoint, similar to `/extended/v1/:address/transactions`.

But rather than returning a bare array of transactions, it would return a list of objects that look like:
```
{
  transaction: <tx object>,
  stx_transfers: <inbound and outbound transfers related to the address requested>
}
```
