### ISSUE TITLE
Paginate tx events in same format as other paginated routes

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain-api#464]
There is no total events returned with the events key in a transaction. It'd be nice if it was there to help know if there are more events to fetch for creating a paginated "load more" component.

**Comment by noumanahmads** [comment]
I am working on this.

**Comment by kyranjamie** [comment]
This will be a breaking change, right?

**Comment by noumanahmads** [comment]
I am updating this [method](https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/datastore/postgres-store.ts#L1698).
Here offset and limit is implemented in multiple queries like this :
```
 SELECT
          event_index, tx_id, tx_index, block_height, canonical, locked_amount, unlock_height, locked_address
        FROM stx_lock_events
        WHERE tx_id = $1 AND index_block_hash = $2 AND event_index BETWEEN $3 AND $4
```
```
SELECT
          event_index, tx_id, tx_index, block_height, canonical, asset_event_type_id, sender, recipient, amount
        FROM stx_events
        WHERE tx_id = $1 AND index_block_hash = $2 AND event_index BETWEEN $3 AND $4
```
```
SELECT
          event_index, tx_id, tx_index, block_height, canonical, asset_event_type_id, sender, recipient, asset_identifier, amount
        FROM ft_events
        WHERE tx_id = $1 AND index_block_hash = $2 AND event_index BETWEEN $3 AND $4
```
```
SELECT
          event_index, tx_id, tx_index, block_height, canonical, asset_event_type_id, sender, recipient, asset_identifier, value
        FROM nft_events
        WHERE tx_id = $1 AND index_block_hash = $2 AND event_index BETWEEN $3 AND $4
```
```
SELECT
          event_index, tx_id, tx_index, block_height, canonical, contract_identifier, topic, value
        FROM contract_logs
        WHERE tx_id = $1 AND index_block_hash = $2 AND event_index BETWEEN $3 AND $4
```

How event index is implemented in these tables? 
For example if `event_index` is 1 in table `stx_events` then it shouldn't exist in any other tables `ft_events`, `nft_events`, `contract_logs`. Is this the case here?

**Comment by zone117x** [comment]
@kyranjamie this is just adding a `total` field to the response, no breaking change. 

@noumanahmad001 for this feature, a `SELECT COUNT(*) OVER() AS count` should be added to those queries, similar to how the `count` (or `total`) number of rows are queried from other areas. For example this query:
https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/datastore/postgres-store.ts#L1513-L1515

**Comment by noumanahmads** [comment]
I am updating this endpoint: 
https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/api/routes/tx.ts#L179
It has the function 
https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/api/controllers/db-controller.ts#L482 
which is returning `Promise<FoundOrNot<Transaction>>`. If I update the method as discussed above I'll have to update the return type of this function which should also include the `totalEvents` (Add `totalEvents` key in `Transaction`)

**or** I can write a separate method for returning the count only instead of updating this one https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/datastore/postgres-store.ts#L1698 To calculate thatl I need `tx_id and index_block_hash`. `tx_id` comes from the query params and `index_block_hash` from this 
https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/api/controllers/db-controller.ts#L489.  This `db.getTx` will be called a couple of times in this approach.


The other thing is, I am thinking of updating the response something like this: 
```
{
      block_hash: '0xff',
      block_height: 123,
      burn_block_time: 1594647995,
      burn_block_time_iso: '2020-07-13T13:46:35.000Z',
      canonical: true,
      tx_id: '0x79abc7783de19569106087302b02379dd02cbb52d20c6c3a7c3d79cbedd559fa',
      tx_index: 2,
      tx_status: 'abort_by_response',
      tx_result: {
        hex: '0x0100000000000000000000000000000001', // u1
        repr: 'u1',
      },
      tx_type: 'smart_contract',
      fee_rate: '200',
      nonce: 0,
      sender_address: 'SP2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7GB36ZAR0',
      sponsored: false,
      post_condition_mode: 'deny',
      post_conditions: [],
      smart_contract: {
        contract_id: 'SP2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7GB36ZAR0.hello-world',
        source_code: '()',
      },
      totalEvents: 0  // new addition
      events: [],
    }
```
Added the key `totalEvents`.  
Please share your thoughts on both of these things. @zone117x

**Comment by zone117x** [comment]
Tough decisions here. 
I think we should add `event_count` here: https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/docs/entities/transactions/abstract-transaction.schema.json#L92

Something like:
```json
    "event_count": {
      "type": "integer",
      "description": "Total number of events in this transaction"
    },
```

Then re-regenerate the `Transaction` type by running `cd docs; npm i; npm run build`

Afterwards, the new `event_count` property will need set within this condition (only for non-mempool transactions):
https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/api/controllers/db-controller.ts#L511

The API would then need to specify the `event_count` for every query that returns transactions, including the endpoints that return a list of transactions. Because of that, I think we'll run into performance problems trying to run an additional expensive `count(*)` query for each transaction. Luckily, this is a static integer, and we can easily just add an `event_count` column to the transaction table. 

So in this table https://github.com/blockstack/stacks-blockchain-api/blob/98404b4f08aff542bfbe5c167a30aa65f34800ae/src/migrations/1584619633448_txs.ts#L4
We'd add:
```js
    event_count: {
      type: 'integer',
      notNull: true,
    },
```
And update the queries in `src/datastore/postgres-store.ts` to fetch the column like the other base transaction columns.

**Comment by noumanahmads** [comment]
so my solution would be add one more key `events_count` in DbTX
https://github.com/blockstack/stacks-blockchain-api/blob/54219ab5dad45c97d8603e3676b92fe937f6e928/src/datastore/common.ts#L107

and `events_count` will be calculated here
https://github.com/blockstack/stacks-blockchain-api/blob/54219ab5dad45c97d8603e3676b92fe937f6e928/src/datastore/postgres-store.ts#L441
`events_count = entry.stxEvents.length  + entry.contractLogEvents.length + entry.stxLockEvents.length + 
                            entry.ftEvents.length + entry.nftEvents.length;`
                            
 I don't know if we have a better approach for calculating the `events_count`. 
 One more thing we should address here is that how `events_count` will be calculated for the transactions which are already in the database.

**Comment by zone117x** [comment]
You can set the `event_count` here https://github.com/blockstack/stacks-blockchain-api/blob/54219ab5dad45c97d8603e3676b92fe937f6e928/src/event-stream/event-server.ts#L360
like 
```ts
  for (const tx of dbData.txs) {
    const sortedEvents = [
      tx.contractLogEvents,
      tx.ftEvents,
      tx.nftEvents,
      tx.stxEvents,
      tx.stxLockEvents,
    ]
      .flat()
      .sort((a, b) => a.event_index - b.event_index);
    tx.event_count = sortedEvents.length; // <----
    for (let i = 0; i < sortedEvents.length; i++) {
      sortedEvents[i].event_index = i;
    }
  }
```

> One more thing we should address here is that how events_count will be calculated for the transactions which are already in the database.

Don't worry about that, the database is wiped on upgrades right now.

**Comment by agraebe** [comment]
this is completed now, right?
