### ISSUE TITLE
BNS: redirect to subdomain registrar for missed subdomains

### ISSUE THREAD

**Issue by hstove** [blockstack/stacks-blockchain-api#517]
We want to replicate some behavior in Stacks 1.0. When a name is requested from `/v1/names/:fully_qualified_subdomain`, proxy the request to the registrar for that name (i.e. https://stacks-node-api-bns.testnet.stacks.co/v1/names/test-registrar.id ).

This allows apps to resolve subdomains that haven't fully registered yet. This behavior is pretty important for apps, otherwise a user cannot sign up and register a subdomain that is usable right away, which breaks auth, storage, etc.

**Comment by zone117x** [comment]
@asimm241 @noumanahmads is this something either of you can look into?

**Comment by asimm241** [comment]
> @asimm241 @noumanahmads is this something either of you can look into?

sure.

**Comment by asimm241** [comment]
@hstove how do I determine the registrar endpoint? 
cc: @jcnelson

**Comment by hstove** [comment]
I am not sure how this was handled in stacks 1.0. There was some kind of mapping on the core node between ID -> registrar URL. I think a short-term fix would be to simply support these mappings through some configuration.

**Comment by diwakergupta** [comment]
> I am not sure how this was handled in stacks 1.0. I think there was some kind of mapping on the core node between ID -> registrar URL. I think a short-term fix would be to simply support these mappings through some configuration.

@jcnelson can you add some context on how this was handled in Stacks 1.0? (this had come up in one of the Monday meetings recently)

**Comment by jcnelson** [comment]
In Stacks 1.0, each name's zone file had an optional `URI` record called `_resolver` which contained the URL to the subdomain registrar.  If the Stacks 1.0 node did not yet have the name record, it would reply with an HTTP 302 to the URL in this record.  The subdomain registrar itself implemented the `/v1/names` endpoint, so it could handle name lookup requests (in fact, the HTTP 302 would be directly to this URL, plus the `/v1/names` path).

For example, for the BNS name `id.blockstack`, the subdomain registrar always included `_resolver IN URI "https://registrar.blockstack.org"` in each zone file it produced via `NAME_UPDATE` transactions.  Then, when a Stacks 1.0 node was asked to handle a name lookup request for, e.g., `new_name.id.blockstack`, it would first look in its own subdomains database and see if `new_name.id.blockstack` existed (and handle the request if so).  If not, it would reply with an HTTP 302 to `https://registrar.blockstack.org/v1/names/new_name.id.blockstack`, and the client would simply ask the subdomain registrar for the name record.

Note that this design requires the subdomain registrar to faithfully emulate the `/v1/names` endpoint that existed in Stacks 1.0.  I'm personally in favor of preserving this behavior, because it would mean that any HTTP client could ask the Stacks blockchain API endpoint for a name and get transparently directed to the registrar for names that were only recently registered.

**Comment by markmhx** [comment]
This enhancement is quite critical for restoring username registration in production apps and should go live before we restore such user paths in our wallet products.

@asimm241 does it look possible to address this by sometime next week?

**Comment by asimm241** [comment]
> This enhancement is quite critical for restoring username registration in production apps and should go live before we restore such user paths in our wallet products.
> 
> @asimm241 does it look possible to address this by sometime next week?
> 
> cc @andresgalante

Yes! I have started working on it.
