### ISSUE TITLE
Faucet not usable for testing stacking because participation is below 25%

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain-api#664]
**Describe the bug**
There are two thresholds described in https://github.com/blockstack/explorer/issues/483 to activate proof of transfer. The current implementation of the faucet returns enough tokens for 1 block reward on testnet. However, 1% of stacked tokens is required for PoX being active, that is 41,000m STX.

**To Reproduce**
1. Go to faucet on sandbox of the explorer, request stacks for stacking.
2. Stack all stacks
3. See on the v2/pox endpoint that is_pox_active is false.

**Expected behavior**
There should be an endpoint to enable pox. The function should stack 1% of the tokens for 12 cycles if pox is not active  (call `stack-stx` of `pox` contract).

If a user requests stacks for stacking and pox is not active, then the function should also stack 1% of the tokens for 12 cycles.

**Additional context**
https://github.com/blockstack/explorer/issues/483
and discussion around https://discord.com/channels/621759717756370964/691807526118883418/865425773090570260

**Comment by zone117x** [comment]
I'd like to get input from @blockstack/blockchain-team on how to resolve this. It sounds like the API _could_ do this assuming it's faucet account has enough funds, but I'd like more input on if that is the best approach.

**Comment by diwakergupta** [comment]
This issue should be re-worded. I believe the real ask is: make sure Stacking is enabled on the testnet (and if not, provide an easy way to enable it, for instance via the sandbox). This is a reasonable ask.

Under the hood, what this likely entails is making sure some testnet genesis accounts send stacking transactions to meet the global threshold. There are many ways we could solve this. My intuition is that this type of functionality does NOT belong in the API: it's not some standard operation that most developers would benefit from; it's really an implementation detail of the testnet environment that Hiro operates.

@friedger if I've understood you correctly, I'd say we should close both this and blockstack/explorer#483 and I can take an action item to follow up on this internally.

Would also love @lgalabru 's input since he navigated a similar challenge in testing PoX on testnet earlier this year.

**Comment by friedger** [comment]
Yes, that is correct. Happy to close these issues. Also for regtest, it should be easy to enable stacking.

**Comment by agraebe** [comment]
Make sense @friedger. Let's close this for now. Please reopen if there's more to discuss

**Comment by diwakergupta** [comment]
Quick follow up here that PoX should get activated on testnet with the next cycle (63)
