### ISSUE TITLE
Remove transferred names from address endpoint

### ISSUE THREAD

**Issue by markmhx** [blockstack/stacks-blockchain-api#714]
Currently it appears that names are still returned by the address endpoint even once they've been transferred to another address.

See https://github.com/blockstack/stacks-wallet-web/issues/1551#issuecomment-897690761

> Hmm digging into this more, the api reports the original owner as the current owner: https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SPTCSBVXZ6KNV7JEMHAV7KJM9183VAP31053H0R4
> 
> However, there was a name transfer event: https://explorer.stacks.co/txid/0x79ad2a1a264d049f13842f0f055f0a40073488c74277fb4a899ec0355d13d8a6?chain=mainnet
> 
> The api shows this account: https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP3JKC09PH0RH8G1XVT031J3E3S0GJ15DEMG7EAZP/assets does infact own the name.
> 
> This is likely an API bug that should be fixed when we have a new deployment, but cc @zone117x to be sure.
> 
> Once microblocks is launched on the api side, we should come back and confirm this is correct.

_Originally posted by @aulneau in https://github.com/blockstack/stacks-wallet-web/issues/1551#issuecomment-897690761_

> Looking into this today, I seem to have the same issue in one of my accounts. This name transfer was successful, but it is still showing up in my wallet: https://explorer.stacks.co/txid/0x30a1a3d18709ddcd70ddb4fb904feeaf3cf5538aa724b7b5e78081fed6395ad0?chain=mainnet
> 
> Transferred from:
> https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP2J1ZFZ5BYTD7H7F84CCZ2B4HEJSBV060XW79G1X
> 
> Transferred to:
> https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP9CMJ7S8XR25H6ZKAJXT4M7KSPQ1B8PPVSYJRTC

_Originally posted by @fbwoolf in https://github.com/blockstack/stacks-wallet-web/issues/1551#issuecomment-898683711_

**Comment by zone117x** [comment]
@asimm241 I think there's a bug in the fix for this issue -- it looks like the last owned name logic is inverted.
In the above example:
> Transferred from:
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP2J1ZFZ5BYTD7H7F84CCZ2B4HEJSBV060XW79G1X
>
> Transferred to:
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP9CMJ7S8XR25H6ZKAJXT4M7KSPQ1B8PPVSYJRTC

Only the original address has the name. 

Looks like the same thing happening with this name: https://github.com/blockstack/stacks-wallet-web/issues/1706
Transferred from:
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP32QQ557KP1Q8DPBGJCZ6NTYXVC41AFK5AR28GGT
to:
https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP3J8H2P4AFH1NK96BJJY9S2V5GW4SCV7MKW7A7P0

**Comment by asimm241** [comment]
The problem was occurring because of name owner was being set incorrectly.  I have created another issue to track that. 
https://github.com/blockstack/stacks-blockchain-api/pull/778

This issue should be closed as it's not a problem with the query.
