### ISSUE TITLE
a few raw transactions are missing (operational issue at stacks-node-api.mainnet.stacks.co)

### ISSUE THREAD

**Issue by fariedt** [blockstack/stacks-blockchain-api#755]
For example, `0xd3d8f40671c6bb24fb4bf7ca6782e96ec3f09f7ef65ace7a02e571ca547b13eb`:

```
$ curl https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0xd3d8f40671c6bb24fb4bf7ca6782e96ec3f09f7ef65ace7a02e571ca547b13eb/raw
{
  "raw_tx": "0x00"
}
$ curl https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0xd3d8f40671c6bb24fb4bf7ca6782e96ec3f09f7ef65ace7a02e571ca547b13eb/
... a seemingly normal stx transfer ...
```

Another one: `0xddafd0fd18f84f2ce8375e08467182a662e0a215cbecbd724b9fc7e4a65f9922`

Several of the ones I've found have the same transferred amount -- 388,888 STX -- and are from multisig address, with a fee of 0 (is that possible?).  I assume it's some internal Blockstack thing.

**Comment by zone117x** [comment]
These are actually special transactions initiated on the bitcoin chain and picked up by the Stacks chain and treated as a Stacks operation. These types of transactions are supported in the API only in the sense that they can be artificially transformed into the results of a regular Stacks transaction, see: https://github.com/blockstack/stacks-blockchain-api/blob/9a7165e3c9a2185684f77145f9d391991981cb82/src/event-stream/reader.ts#L243-L267

Certain properties like "raw stx tx" don't exist for these txs, which is why only this null-byte `0x00` is returned. 

You can find some more context on these in the API from these PRs:
https://github.com/blockstack/stacks-blockchain-api/pull/414
https://github.com/blockstack/stacks-blockchain-api/pull/400
https://github.com/blockstack/stacks-blockchain-api/pull/398

**Comment by zone117x** [comment]
I'm not sure if there's anything actionable to do here so I'm going to close the issue for now. Please comment if you think there is.
