### ISSUE TITLE
Broadcast to `STACKS_CORE_RPC_HOST` and `STACKS_CORE_PROXY_HOST` on `/v2/transactions`

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain-api#765]
**Is your feature request related to a problem? Please describe.**

Typical API configurations set the event-emitting stacks-node to `STACKS_CORE_RPC_HOST` and a pool of RPC handling followers to `STACKS_CORE_PROXY_HOST`. When `/v2/transactions` POSTs are handled, the event emitter needs to get the transaction to update the API's mempool endpoints, but if it isn't getting broadcasted to directly, there may be a delay in that node processing the event (or it may get missed entirely). 

**Describe the solution you'd like**

The API router (src/api/routes/core-node-rpc-proxy.ts) should forward `/v2/transactions` POSTs to both the `STACKS_CORE_RPC_HOST` and the `STACKS_CORE_PROXY_HOST`.

**Comment by wileyj** [comment]
adding some possibly relevant files:
https://github.com/blockstack/stacks-blockchain-api/blob/master/src/api/routes/core-node-rpc-proxy.ts
https://github.com/blockstack/stacks-blockchain-api/blob/master/src/core-rpc/client.ts#L193-L202

**Comment by zone117x** [comment]
I'm open to doing this as a temporary fix to the mempool propagation issues, however, it's not without several issues:
1. We don't expose the event emitter node to the public because excess load can cause API updates to slow down or halt.
2. This change increases infrastructure dependency issues related to https://github.com/blockstack/stacks-blockchain-api/issues/642
3. This will paper over the underlying problem with mempool propagation that will continue to affect other nodes, like other API deployments and presumably miner nodes.

It sounds like the underlying issue should be captured in the stacks-blockchain repo so that we're tracking it despite implementing a temporary workaround in the API.

**Comment by zone117x** [comment]
[informational] here's the issue tracking improvements to the tx mempool propagation code: https://github.com/blockstack/stacks-blockchain/issues/2193

**Comment by agraebe** [comment]
with the linked PR merged and the stacks node ref issue, can this be closed @zone117x
